---
abstract: 'Wikibase cache backend to local static basic ids (units, common properties).'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wikibase-Cache-Backend-Basic
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.03
  Error::Pure: 0.15
  Text::DSV: 0
  Wikibase::Cache::Backend: 0.03
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Wikibase-Cache-Backend-Basic/issues
  homepage: https://github.com/michal-josef-spacek/Wikibase-Cache-Backend-Basic
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Wikibase-Cache-Backend-Basic
version: '0.02'
